name: moveapps-python-sdk
channels:
  - conda-forge
  - defaults
dependencies:
  - qgis=3.8.1
  - urllib3=1.26.15=pyhd8ed1ab_0
  - pyproj
  - matplotlib
  - branca
  - folium
  - numpy
  - geopandas
  - movingpandas
  - shapely
  - scipy
  - pluggy
  - python-dotenv
