name: test

on: [push]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64
      - name: Test via build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: false
